name: " WEB [CD]"

on:
  push:
    branches:
      - 'dev'
      - 'ops'
      - 'main'
    paths:
      - 'build/package/web/**'
      - 'web/**'
      - '.github/**'


jobs:
  BUILD:
    name: BUILD
    runs-on: ubuntu-latest
    env:
      wd: web/
    steps:
      # Checkout to current workspace
    - name: 1 - CHECKOUT
      uses: actions/checkout@v2

      # Install Golang with specific version
    - name: 2 - SETUP NODE@18
      uses:  actions/setup-node@v3
      with:
          node-version: 18

      # Cache Go modules to make the build faster
    - name: 3 - CACHE NODE MODULES
      uses: actions/cache@v2
      with:
        path: |
          web/node_modules
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-

    # Install packages
    - name: 3 - NPM INSTALL
      run: npm install
      working-directory: ${{ env.wd }}

    # Build apps
    - name: 4 - BUILD
      run: npm run build
      working-directory: ${{ env.wd }}
      env:
        CI: "" 

  RELEASE:
    name: RELEASE
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      # Checkout to current workspace
      - name: 1 - CHECKOUT
        uses: actions/checkout@v2

        # Login to container registry
      - name: 2 - LOGIN TO GHCR.IO
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GPAT }}

      # Setup custom tag name
      - name: 3 - SETUP ENV VARS
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | head -c8)" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date +%Y%m%d%H%M)"                >> $GITHUB_ENV
          echo "BRANCH_NAME=$GITHUB_REF_NAME"                    >> $GITHUB_ENV

        # Build and push the app with given file and tag
      - name: 4 - BUILD + PUSH
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: build/package/web/Dockerfile.prod
          tags: |
            ghcr.io/blyndusk/tf-gui_web:${{ env.BRANCH_NAME }}-${{ env.GITHUB_SHA_SHORT }}-${{ env.CURRENT_DATE }}
            ghcr.io/blyndusk/tf-gui_web:${{ env.BRANCH_NAME }}-${{ env.GITHUB_SHA_SHORT }}
            ghcr.io/blyndusk/tf-gui_web:latest

        # output the logs
      - name: 5 - IMAGE DIGEST
        run: echo ${{ steps.docker_build.outputs.digest }}
